spring:
    application:
        name: articlecheck
    jpa:
        hibernate:
            ddl-auto: create-drop
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
                format_sql: true
    datasource:
        url: jdbc:mysql://localhost:3306/${DB_NAME}?createDatabaseIfNotExist=true
        username: ${DB_USERNAME}
        password: ${DB_PASSWORD}
        driverClassName: com.mysql.cj.jdbc.Driver
    mail:
        host: smtp.gmail.com
        port: 587
        username: ${MAIL_USERNAME}
        password: ${MAIL_PASSWORD}
        properties:
            mail:
                smtp:
                    auth: true
                    starttls:
                        enable: true

openai:
  api:
    key: ${OPENAI_API_KEY}
    url: https://api.openai.com/v1/chat/completions

file:
    upload:
        dir: ${java.io.tmpdir}/essay-uploads

server:
    port: 8080
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    com.trinhhoctuan.articlecheck: DEBUG